### ISSUE TITLE
 Reason for loss does not falling

### ISSUE THREAD

**Issue by 980044579** [opconty/pytorch_ctpn#15]
Thank you for sharing your project !
There is no problem with the code logic. The reason why the loss does not fall may be that the positive and negative samples are not balanced, and it is not known whether the author makes adjustments to the ratio of positive and negative samples.

**Comment by opconty** [comment]
Thanks for your comment.
Maybe I should check the article again.Or re-implement this model adopting some new methods,such as OHEM, Would be appreciate if you give me some advices.

**Comment by xiiiiiiii** [comment]
数据集和预训练参数挂了，可以求一份连接吗？
