### ISSUE TITLE
识别效果

### ISSUE THREAD

**Issue by Douhana** [opconty/pytorch_ctpn#23]
您最后实现的安卓OCR如果直接给一整张运单效果怎么样？我这边如果像您demo里一样取一小块效果还行，但是一整张运单，加上褶皱模糊污渍等效果简直不能看，您有解决这方面的问题吗

**Comment by opconty** [comment]
您好，这个问题私聊哈

**Comment by Douhana** [comment]
我给您发了邮件，期待您的指导

**Comment by opconty** [comment]
好的,互相交流,不敢指导[捂脸.gif]

**Comment by Douhana** [comment]
您的邮箱是主页的谷歌邮箱吗，我之前给您发过3封，但都没有回（小声）[技术菜只能脸皮厚了]

**Comment by opconty** [comment]
好的, 抱歉不长登那个邮箱,我立刻检查一下
