### ISSUE TITLE
请问一下显存炸了怎么办

### ISSUE THREAD

**Issue by gxxie** [opconty/pytorch_ctpn#30]
小白一枚，作者给的链接都炸了，数据集我用的icdar2013转成了voc。请问是什么问题，还能提供一下原数据集吗

**Comment by opconty** [comment]
炸了是 out of memory 还是不收敛？

原始数据集可以从readme提供的keras版本中下载，网盘容量有限，分享不了了，抱歉

**Comment by gxxie** [comment]
> 炸了是 out of memory 还是不收敛？
> 
> 原始数据集可以从readme提供的keras版本中下载，网盘容量有限，分享不了了，抱歉

是oom了，不知道是不是图片尺寸太大了

**Comment by xieguoxuan** [comment]
> 炸了是 out of memory 还是不收敛？
> 
> 原始数据集可以从readme提供的keras版本中下载，网盘容量有限，分享不了了，抱歉

请问用的是keras版本的ctpn那个数据集？那个Synthetic Chinese String Dataset？

**Comment by gxxie** [comment]
> 炸了是 out of memory 还是不收敛？
> 
> 原始数据集可以从readme提供的keras版本中下载，网盘容量有限，分享不了了，抱歉

请问用的是keras版本的ctpn那个数据集？但是那个也不是voc格式呀？

**Comment by gxxie** [comment]
> 炸了是 out of memory 还是不收敛？
> 
> 原始数据集可以从readme提供的keras版本中下载，网盘容量有限，分享不了了，抱歉

请问一下，下载了新的这个weight链接，运行出现了这个问题是？
using pretrained weight: ./checkpoints/ctpn_keras_weights.pth.tar
Traceback (most recent call last):
  File "ctpn_train.py", line 66, in <module>
    resume_epoch = cc['epoch']
KeyError: 'epoch'

**Comment by gxxie** [comment]
> 炸了是 out of memory 还是不收敛？
> 
> 原始数据集可以从readme提供的keras版本中下载，网盘容量有限，分享不了了，抱歉

我想我知道了，应该是图片尺寸太大了，数据集没有，我就用的icdar2013，里面的某些图片过大，进行一下resize应该就可以；
