### ISSUE TITLE
能再分享一下你训练好的模型吗

### ISSUE THREAD

**Issue by Sierkinhane** [opconty/pytorch_ctpn#4]

**Comment by gwsbhqt** [comment]
@Sierkinhane 把这个pytorch_ctpn和crnn_chinese_characters_rec结合在一起能做个通用的ocr，我挺期待的

**Comment by opconty** [comment]
sorry for late reply
For a number of reasons, the pretrained weights will no longer be available.Thanks for your attention.

**Comment by Crescentz** [comment]
@gwsbhqt 现在没有这样的repo么？ 将CTPN和CRNN结合在一起的？我看有CHINESE-OCR和chinese-ocr
