### ISSUE TITLE
为什么您在model的forward函数把输入的channel first和channel last来回倒？一直channel first不行吗？

### ISSUE THREAD

**Issue by HandsomeBrotherShuaiLi** [opconty/pytorch_ctpn#7]
https://github.com/opconty/pytorch_ctpn/blob/d1723c68f8549937a5480c64a08f5726b5601d10/ctpn_model.py#L106

**Comment by kiiokiio** [comment]
我也有此疑问，不过看了 training log之后就感觉了解了一些[training log](https://github.com/opconty/pytorch_ctpn/blob/master/logs/training_logs.pdf)。pytorch是channel first， 变换之后方便lstm进行处理。【个人理解，有偏差欢迎指正啊】

**Comment by HandsomeBrotherShuaiLi** [comment]
我懂了，是因为LSTM输入的问题。
